import { forwardRef } from 'react'
import hero from '../generated/hero.svg?raw'

/* The pendant, face-on, generated by build.py from the same screen markup the exploded
   drawing uses -- so the site has one proposal screen and it is the firmware's. Shown
   whenever the opening cannot run: on a phone, and wherever motion is reduced. */
const PendantStatic = forwardRef<HTMLElement>(function PendantStatic(_props, ref) {
  return (
    <figure className="device" ref={ref as React.Ref<HTMLElement>}>
      <div className="facewrap" dangerouslySetInnerHTML={{ __html: hero }} />
      <figcaption>
        <span><b>240 &#215; 240</b> round display</span>
        <span><b>ESP32-S3</b> &#183; Wi-Fi + Bluetooth</span>
        <span><b>Haptic</b> &#183; three tiers</span>
        <span><b>No key</b> stored on board</span>
      </figcaption>
    </figure>
  )
})
export default PendantStatic
